/*
 * Caspian.Yes4Track.Service API
 * Caspian.Yes4Track.Service API
 *
 * OpenAPI spec version: v1
 * Contact: admin@yes4track.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The DocumentVersion model module.
 * @module model/DocumentVersion
 * @version v1
 */
export class DocumentVersion {
  /**
   * Constructs a new <code>DocumentVersion</code>.
   * @alias module:model/DocumentVersion
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>DocumentVersion</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DocumentVersion} obj Optional instance to populate.
   * @return {module:model/DocumentVersion} The populated <code>DocumentVersion</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DocumentVersion();
    }
    return obj;
  }
}
