/*
 * Caspian.Yes4Track.Service API
 * Caspian.Yes4Track.Service API
 *
 * OpenAPI spec version: v1
 * Contact: admin@yes4track.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The GetAllAdventureLikesResponse model module.
 * @module model/GetAllAdventureLikesResponse
 * @version v1
 */
export class GetAllAdventureLikesResponse {
  /**
   * Constructs a new <code>GetAllAdventureLikesResponse</code>.
   * @alias module:model/GetAllAdventureLikesResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GetAllAdventureLikesResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetAllAdventureLikesResponse} obj Optional instance to populate.
   * @return {module:model/GetAllAdventureLikesResponse} The populated <code>GetAllAdventureLikesResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetAllAdventureLikesResponse();
      if (data.hasOwnProperty('createdAt'))
        obj.createdAt = ApiClient.convertToType(data['createdAt'], 'Date');
      if (data.hasOwnProperty('updatedAt'))
        obj.updatedAt = ApiClient.convertToType(data['updatedAt'], 'Date');
      if (data.hasOwnProperty('userCreated'))
        obj.userCreated = ApiClient.convertToType(data['userCreated'], 'String');
      if (data.hasOwnProperty('userUpdated'))
        obj.userUpdated = ApiClient.convertToType(data['userUpdated'], 'String');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('adventureId'))
        obj.adventureId = ApiClient.convertToType(data['adventureId'], 'String');
      if (data.hasOwnProperty('userName'))
        obj.userName = ApiClient.convertToType(data['userName'], 'String');
      if (data.hasOwnProperty('userPhoto'))
        obj.userPhoto = ApiClient.convertToType(data['userPhoto'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Date} createdAt
 */
GetAllAdventureLikesResponse.prototype.createdAt = undefined;

/**
 * @member {Date} updatedAt
 */
GetAllAdventureLikesResponse.prototype.updatedAt = undefined;

/**
 * @member {String} userCreated
 */
GetAllAdventureLikesResponse.prototype.userCreated = undefined;

/**
 * @member {String} userUpdated
 */
GetAllAdventureLikesResponse.prototype.userUpdated = undefined;

/**
 * @member {String} id
 */
GetAllAdventureLikesResponse.prototype.id = undefined;

/**
 * @member {String} adventureId
 */
GetAllAdventureLikesResponse.prototype.adventureId = undefined;

/**
 * @member {String} userName
 */
GetAllAdventureLikesResponse.prototype.userName = undefined;

/**
 * @member {String} userPhoto
 */
GetAllAdventureLikesResponse.prototype.userPhoto = undefined;

