/*
 * Caspian.Yes4Track.Service API
 * Caspian.Yes4Track.Service API
 *
 * OpenAPI spec version: v1
 * Contact: admin@yes4track.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The GetByIdAdventureCodeResponse model module.
 * @module model/GetByIdAdventureCodeResponse
 * @version v1
 */
export class GetByIdAdventureCodeResponse {
  /**
   * Constructs a new <code>GetByIdAdventureCodeResponse</code>.
   * @alias module:model/GetByIdAdventureCodeResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GetByIdAdventureCodeResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetByIdAdventureCodeResponse} obj Optional instance to populate.
   * @return {module:model/GetByIdAdventureCodeResponse} The populated <code>GetByIdAdventureCodeResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetByIdAdventureCodeResponse();
      if (data.hasOwnProperty('code'))
        obj.code = ApiClient.convertToType(data['code'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} code
 */
GetByIdAdventureCodeResponse.prototype.code = undefined;

