/*
 * Caspian.Yes4Track.Service API
 * Caspian.Yes4Track.Service API
 *
 * OpenAPI spec version: v1
 * Contact: admin@yes4track.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The GetUserLikedAdventureResponse model module.
 * @module model/GetUserLikedAdventureResponse
 * @version v1
 */
export class GetUserLikedAdventureResponse {
  /**
   * Constructs a new <code>GetUserLikedAdventureResponse</code>.
   * @alias module:model/GetUserLikedAdventureResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GetUserLikedAdventureResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetUserLikedAdventureResponse} obj Optional instance to populate.
   * @return {module:model/GetUserLikedAdventureResponse} The populated <code>GetUserLikedAdventureResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetUserLikedAdventureResponse();
      if (data.hasOwnProperty('userLiked'))
        obj.userLiked = ApiClient.convertToType(data['userLiked'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {Boolean} userLiked
 */
GetUserLikedAdventureResponse.prototype.userLiked = undefined;

