/*
 * Caspian.Yes4Track.Service API
 * Caspian.Yes4Track.Service API
 *
 * OpenAPI spec version: v1
 * Contact: admin@yes4track.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The IdGeodataBody1 model module.
 * @module model/IdGeodataBody1
 * @version v1
 */
export class IdGeodataBody1 {
  /**
   * Constructs a new <code>IdGeodataBody1</code>.
   * @alias module:model/IdGeodataBody1
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IdGeodataBody1</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IdGeodataBody1} obj Optional instance to populate.
   * @return {module:model/IdGeodataBody1} The populated <code>IdGeodataBody1</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IdGeodataBody1();
      if (data.hasOwnProperty('files'))
        obj.files = ApiClient.convertToType(data['files'], ['Blob']);
    }
    return obj;
  }
}

/**
 * Files
 * @member {Array.<Blob>} files
 */
IdGeodataBody1.prototype.files = undefined;

