/*
 * Caspian.Yes4Track.Service API
 * Caspian.Yes4Track.Service API
 *
 * OpenAPI spec version: v1
 * Contact: admin@yes4track.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The IdImagesBody1 model module.
 * @module model/IdImagesBody1
 * @version v1
 */
export class IdImagesBody1 {
  /**
   * Constructs a new <code>IdImagesBody1</code>.
   * @alias module:model/IdImagesBody1
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IdImagesBody1</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IdImagesBody1} obj Optional instance to populate.
   * @return {module:model/IdImagesBody1} The populated <code>IdImagesBody1</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IdImagesBody1();
      if (data.hasOwnProperty('images'))
        obj.images = ApiClient.convertToType(data['images'], ['Blob']);
    }
    return obj;
  }
}

/**
 * Images
 * @member {Array.<Blob>} images
 */
IdImagesBody1.prototype.images = undefined;

