/*
 * Caspian.Yes4Track.Service API
 * Caspian.Yes4Track.Service API
 *
 * OpenAPI spec version: v1
 * Contact: admin@yes4track.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The IdVideosBody model module.
 * @module model/IdVideosBody
 * @version v1
 */
export class IdVideosBody {
  /**
   * Constructs a new <code>IdVideosBody</code>.
   * @alias module:model/IdVideosBody
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IdVideosBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IdVideosBody} obj Optional instance to populate.
   * @return {module:model/IdVideosBody} The populated <code>IdVideosBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IdVideosBody();
      if (data.hasOwnProperty('videos'))
        obj.videos = ApiClient.convertToType(data['videos'], ['Blob']);
    }
    return obj;
  }
}

/**
 * Videos
 * @member {Array.<Blob>} videos
 */
IdVideosBody.prototype.videos = undefined;

