/*
 * Caspian.Yes4Track.Service API
 * Caspian.Yes4Track.Service API
 *
 * OpenAPI spec version: v1
 * Contact: admin@yes4track.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The PostUserSetupAngelRequest model module.
 * @module model/PostUserSetupAngelRequest
 * @version v1
 */
export class PostUserSetupAngelRequest {
  /**
   * Constructs a new <code>PostUserSetupAngelRequest</code>.
   * @alias module:model/PostUserSetupAngelRequest
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>PostUserSetupAngelRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PostUserSetupAngelRequest} obj Optional instance to populate.
   * @return {module:model/PostUserSetupAngelRequest} The populated <code>PostUserSetupAngelRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PostUserSetupAngelRequest();
      if (data.hasOwnProperty('createdAt'))
        obj.createdAt = ApiClient.convertToType(data['createdAt'], 'Date');
      if (data.hasOwnProperty('updatedAt'))
        obj.updatedAt = ApiClient.convertToType(data['updatedAt'], 'Date');
      if (data.hasOwnProperty('userCreated'))
        obj.userCreated = ApiClient.convertToType(data['userCreated'], 'String');
      if (data.hasOwnProperty('userUpdated'))
        obj.userUpdated = ApiClient.convertToType(data['userUpdated'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('phone'))
        obj.phone = ApiClient.convertToType(data['phone'], 'String');
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Date} createdAt
 */
PostUserSetupAngelRequest.prototype.createdAt = undefined;

/**
 * @member {Date} updatedAt
 */
PostUserSetupAngelRequest.prototype.updatedAt = undefined;

/**
 * @member {String} userCreated
 */
PostUserSetupAngelRequest.prototype.userCreated = undefined;

/**
 * @member {String} userUpdated
 */
PostUserSetupAngelRequest.prototype.userUpdated = undefined;

/**
 * @member {String} name
 */
PostUserSetupAngelRequest.prototype.name = undefined;

/**
 * @member {String} phone
 */
PostUserSetupAngelRequest.prototype.phone = undefined;

/**
 * @member {String} email
 */
PostUserSetupAngelRequest.prototype.email = undefined;

