/*
 * Caspian.Yes4Track.Service API
 * Caspian.Yes4Track.Service API
 *
 * OpenAPI spec version: v1
 * Contact: admin@yes4track.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The PostUserSignInResponse model module.
 * @module model/PostUserSignInResponse
 * @version v1
 */
export class PostUserSignInResponse {
  /**
   * Constructs a new <code>PostUserSignInResponse</code>.
   * @alias module:model/PostUserSignInResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>PostUserSignInResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PostUserSignInResponse} obj Optional instance to populate.
   * @return {module:model/PostUserSignInResponse} The populated <code>PostUserSignInResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PostUserSignInResponse();
      if (data.hasOwnProperty('message'))
        obj.message = ApiClient.convertToType(data['message'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} message
 */
PostUserSignInResponse.prototype.message = undefined;

