/*
 * Caspian.Yes4Track.Service API
 * Caspian.Yes4Track.Service API
 *
 * OpenAPI spec version: v1
 * Contact: admin@yes4track.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {TrackSource} from './TrackSource';

/**
 * The PostTrackRequest model module.
 * @module model/PostTrackRequest
 * @version v1
 */
export class PostTrackRequest {
  /**
   * Constructs a new <code>PostTrackRequest</code>.
   * @alias module:model/PostTrackRequest
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>PostTrackRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PostTrackRequest} obj Optional instance to populate.
   * @return {module:model/PostTrackRequest} The populated <code>PostTrackRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PostTrackRequest();
      if (data.hasOwnProperty('createdAt'))
        obj.createdAt = ApiClient.convertToType(data['createdAt'], 'Date');
      if (data.hasOwnProperty('updatedAt'))
        obj.updatedAt = ApiClient.convertToType(data['updatedAt'], 'Date');
      if (data.hasOwnProperty('userCreated'))
        obj.userCreated = ApiClient.convertToType(data['userCreated'], 'String');
      if (data.hasOwnProperty('userUpdated'))
        obj.userUpdated = ApiClient.convertToType(data['userUpdated'], 'String');
      if (data.hasOwnProperty('adventureId'))
        obj.adventureId = ApiClient.convertToType(data['adventureId'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('source'))
        obj.source = TrackSource.constructFromObject(data['source']);
      if (data.hasOwnProperty('startDate'))
        obj.startDate = ApiClient.convertToType(data['startDate'], 'Date');
      if (data.hasOwnProperty('endDate'))
        obj.endDate = ApiClient.convertToType(data['endDate'], 'Date');
    }
    return obj;
  }
}

/**
 * @member {Date} createdAt
 */
PostTrackRequest.prototype.createdAt = undefined;

/**
 * @member {Date} updatedAt
 */
PostTrackRequest.prototype.updatedAt = undefined;

/**
 * @member {String} userCreated
 */
PostTrackRequest.prototype.userCreated = undefined;

/**
 * @member {String} userUpdated
 */
PostTrackRequest.prototype.userUpdated = undefined;

/**
 * @member {String} adventureId
 */
PostTrackRequest.prototype.adventureId = undefined;

/**
 * @member {String} name
 */
PostTrackRequest.prototype.name = undefined;

/**
 * @member {module:model/TrackSource} source
 */
PostTrackRequest.prototype.source = undefined;

/**
 * @member {Date} startDate
 */
PostTrackRequest.prototype.startDate = undefined;

/**
 * @member {Date} endDate
 */
PostTrackRequest.prototype.endDate = undefined;

