/*
 * Caspian.Yes4Track.Service API
 * Caspian.Yes4Track.Service API
 *
 * OpenAPI spec version: v1
 * Contact: admin@yes4track.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The PostCheckAdventureCodeResponse model module.
 * @module model/PostCheckAdventureCodeResponse
 * @version v1
 */
export class PostCheckAdventureCodeResponse {
  /**
   * Constructs a new <code>PostCheckAdventureCodeResponse</code>.
   * @alias module:model/PostCheckAdventureCodeResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>PostCheckAdventureCodeResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PostCheckAdventureCodeResponse} obj Optional instance to populate.
   * @return {module:model/PostCheckAdventureCodeResponse} The populated <code>PostCheckAdventureCodeResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PostCheckAdventureCodeResponse();
      if (data.hasOwnProperty('isSuccess'))
        obj.isSuccess = ApiClient.convertToType(data['isSuccess'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {Boolean} isSuccess
 */
PostCheckAdventureCodeResponse.prototype.isSuccess = undefined;

