/*
 * Caspian.Yes4Track.Service API
 * Caspian.Yes4Track.Service API
 *
 * OpenAPI spec version: v1
 * Contact: admin@yes4track.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The PostTrailPhotosResponse model module.
 * @module model/PostTrailPhotosResponse
 * @version v1
 */
export class PostTrailPhotosResponse {
  /**
   * Constructs a new <code>PostTrailPhotosResponse</code>.
   * @alias module:model/PostTrailPhotosResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>PostTrailPhotosResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PostTrailPhotosResponse} obj Optional instance to populate.
   * @return {module:model/PostTrailPhotosResponse} The populated <code>PostTrailPhotosResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PostTrailPhotosResponse();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('fileName'))
        obj.fileName = ApiClient.convertToType(data['fileName'], 'String');
      if (data.hasOwnProperty('url'))
        obj.url = ApiClient.convertToType(data['url'], 'String');
      if (data.hasOwnProperty('sequence'))
        obj.sequence = ApiClient.convertToType(data['sequence'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
PostTrailPhotosResponse.prototype.id = undefined;

/**
 * @member {String} fileName
 */
PostTrailPhotosResponse.prototype.fileName = undefined;

/**
 * @member {String} url
 */
PostTrailPhotosResponse.prototype.url = undefined;

/**
 * @member {Number} sequence
 */
PostTrailPhotosResponse.prototype.sequence = undefined;

