/*
 * Caspian.Yes4Track.Service API
 * Caspian.Yes4Track.Service API
 *
 * OpenAPI spec version: v1
 * Contact: admin@yes4track.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The PostTrackGeoDataResponse model module.
 * @module model/PostTrackGeoDataResponse
 * @version v1
 */
export class PostTrackGeoDataResponse {
  /**
   * Constructs a new <code>PostTrackGeoDataResponse</code>.
   * @alias module:model/PostTrackGeoDataResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>PostTrackGeoDataResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PostTrackGeoDataResponse} obj Optional instance to populate.
   * @return {module:model/PostTrackGeoDataResponse} The populated <code>PostTrackGeoDataResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PostTrackGeoDataResponse();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('trackId'))
        obj.trackId = ApiClient.convertToType(data['trackId'], 'String');
      if (data.hasOwnProperty('fileName'))
        obj.fileName = ApiClient.convertToType(data['fileName'], 'String');
      if (data.hasOwnProperty('extension'))
        obj.extension = ApiClient.convertToType(data['extension'], 'String');
      if (data.hasOwnProperty('data'))
        obj.data = ApiClient.convertToType(data['data'], 'String');
      if (data.hasOwnProperty('version'))
        obj.version = ApiClient.convertToType(data['version'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
PostTrackGeoDataResponse.prototype.id = undefined;

/**
 * @member {String} trackId
 */
PostTrackGeoDataResponse.prototype.trackId = undefined;

/**
 * @member {String} fileName
 */
PostTrackGeoDataResponse.prototype.fileName = undefined;

/**
 * @member {String} extension
 */
PostTrackGeoDataResponse.prototype.extension = undefined;

/**
 * @member {String} data
 */
PostTrackGeoDataResponse.prototype.data = undefined;

/**
 * @member {String} version
 */
PostTrackGeoDataResponse.prototype.version = undefined;

