/*
 * Caspian.Yes4Track.Service API
 * Caspian.Yes4Track.Service API
 *
 * OpenAPI spec version: v1
 * Contact: admin@yes4track.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ProfilePhotoRequest model module.
 * @module model/ProfilePhotoRequest
 * @version v1
 */
export class ProfilePhotoRequest {
  /**
   * Constructs a new <code>ProfilePhotoRequest</code>.
   * @alias module:model/ProfilePhotoRequest
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ProfilePhotoRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ProfilePhotoRequest} obj Optional instance to populate.
   * @return {module:model/ProfilePhotoRequest} The populated <code>ProfilePhotoRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ProfilePhotoRequest();
      if (data.hasOwnProperty('data'))
        obj.data = ApiClient.convertToType(data['data'], 'Blob');
      if (data.hasOwnProperty('extension'))
        obj.extension = ApiClient.convertToType(data['extension'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Blob} data
 */
ProfilePhotoRequest.prototype.data = undefined;

/**
 * @member {String} extension
 */
ProfilePhotoRequest.prototype.extension = undefined;

