/*
 * Caspian.Yes4Track.Service API
 * Caspian.Yes4Track.Service API
 *
 * OpenAPI spec version: v1
 * Contact: admin@yes4track.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {AdventureType} from './AdventureType';
import {LevelType} from './LevelType';

/**
 * The PutAdventureRequest model module.
 * @module model/PutAdventureRequest
 * @version v1
 */
export class PutAdventureRequest {
  /**
   * Constructs a new <code>PutAdventureRequest</code>.
   * @alias module:model/PutAdventureRequest
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>PutAdventureRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PutAdventureRequest} obj Optional instance to populate.
   * @return {module:model/PutAdventureRequest} The populated <code>PutAdventureRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PutAdventureRequest();
      if (data.hasOwnProperty('createdAt'))
        obj.createdAt = ApiClient.convertToType(data['createdAt'], 'Date');
      if (data.hasOwnProperty('updatedAt'))
        obj.updatedAt = ApiClient.convertToType(data['updatedAt'], 'Date');
      if (data.hasOwnProperty('userCreated'))
        obj.userCreated = ApiClient.convertToType(data['userCreated'], 'String');
      if (data.hasOwnProperty('userUpdated'))
        obj.userUpdated = ApiClient.convertToType(data['userUpdated'], 'String');
      if (data.hasOwnProperty('companyId'))
        obj.companyId = ApiClient.convertToType(data['companyId'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('level'))
        obj.level = LevelType.constructFromObject(data['level']);
      if (data.hasOwnProperty('effectiveStartDate'))
        obj.effectiveStartDate = ApiClient.convertToType(data['effectiveStartDate'], 'Date');
      if (data.hasOwnProperty('effectiveEndDate'))
        obj.effectiveEndDate = ApiClient.convertToType(data['effectiveEndDate'], 'Date');
      if (data.hasOwnProperty('type'))
        obj.type = AdventureType.constructFromObject(data['type']);
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('codeRequired'))
        obj.codeRequired = ApiClient.convertToType(data['codeRequired'], 'Boolean');
      if (data.hasOwnProperty('isActive'))
        obj.isActive = ApiClient.convertToType(data['isActive'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {Date} createdAt
 */
PutAdventureRequest.prototype.createdAt = undefined;

/**
 * @member {Date} updatedAt
 */
PutAdventureRequest.prototype.updatedAt = undefined;

/**
 * @member {String} userCreated
 */
PutAdventureRequest.prototype.userCreated = undefined;

/**
 * @member {String} userUpdated
 */
PutAdventureRequest.prototype.userUpdated = undefined;

/**
 * @member {String} companyId
 */
PutAdventureRequest.prototype.companyId = undefined;

/**
 * @member {String} name
 */
PutAdventureRequest.prototype.name = undefined;

/**
 * @member {String} description
 */
PutAdventureRequest.prototype.description = undefined;

/**
 * @member {module:model/LevelType} level
 */
PutAdventureRequest.prototype.level = undefined;

/**
 * @member {Date} effectiveStartDate
 */
PutAdventureRequest.prototype.effectiveStartDate = undefined;

/**
 * @member {Date} effectiveEndDate
 */
PutAdventureRequest.prototype.effectiveEndDate = undefined;

/**
 * @member {module:model/AdventureType} type
 */
PutAdventureRequest.prototype.type = undefined;

/**
 * @member {String} id
 */
PutAdventureRequest.prototype.id = undefined;

/**
 * @member {Boolean} codeRequired
 */
PutAdventureRequest.prototype.codeRequired = undefined;

/**
 * @member {Boolean} isActive
 */
PutAdventureRequest.prototype.isActive = undefined;

