/*
 * Caspian.Yes4Track.Service API
 * Caspian.Yes4Track.Service API
 *
 * OpenAPI spec version: v1
 * Contact: admin@yes4track.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {CompanyType} from './CompanyType';
import {ProfilePhotoRequest} from './ProfilePhotoRequest';
import {RegistrationType} from './RegistrationType';

/**
 * The PutCompanyRequest model module.
 * @module model/PutCompanyRequest
 * @version v1
 */
export class PutCompanyRequest {
  /**
   * Constructs a new <code>PutCompanyRequest</code>.
   * @alias module:model/PutCompanyRequest
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>PutCompanyRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PutCompanyRequest} obj Optional instance to populate.
   * @return {module:model/PutCompanyRequest} The populated <code>PutCompanyRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PutCompanyRequest();
      if (data.hasOwnProperty('createdAt'))
        obj.createdAt = ApiClient.convertToType(data['createdAt'], 'Date');
      if (data.hasOwnProperty('updatedAt'))
        obj.updatedAt = ApiClient.convertToType(data['updatedAt'], 'Date');
      if (data.hasOwnProperty('userCreated'))
        obj.userCreated = ApiClient.convertToType(data['userCreated'], 'String');
      if (data.hasOwnProperty('userUpdated'))
        obj.userUpdated = ApiClient.convertToType(data['userUpdated'], 'String');
      if (data.hasOwnProperty('legalName'))
        obj.legalName = ApiClient.convertToType(data['legalName'], 'String');
      if (data.hasOwnProperty('fantasyName'))
        obj.fantasyName = ApiClient.convertToType(data['fantasyName'], 'String');
      if (data.hasOwnProperty('registrationNumber'))
        obj.registrationNumber = ApiClient.convertToType(data['registrationNumber'], 'String');
      if (data.hasOwnProperty('registrationType'))
        obj.registrationType = RegistrationType.constructFromObject(data['registrationType']);
      if (data.hasOwnProperty('contactEmail'))
        obj.contactEmail = ApiClient.convertToType(data['contactEmail'], 'String');
      if (data.hasOwnProperty('contactPhone'))
        obj.contactPhone = ApiClient.convertToType(data['contactPhone'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = CompanyType.constructFromObject(data['type']);
      if (data.hasOwnProperty('biography'))
        obj.biography = ApiClient.convertToType(data['biography'], 'String');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('profilePhoto'))
        obj.profilePhoto = ProfilePhotoRequest.constructFromObject(data['profilePhoto']);
    }
    return obj;
  }
}

/**
 * @member {Date} createdAt
 */
PutCompanyRequest.prototype.createdAt = undefined;

/**
 * @member {Date} updatedAt
 */
PutCompanyRequest.prototype.updatedAt = undefined;

/**
 * @member {String} userCreated
 */
PutCompanyRequest.prototype.userCreated = undefined;

/**
 * @member {String} userUpdated
 */
PutCompanyRequest.prototype.userUpdated = undefined;

/**
 * @member {String} legalName
 */
PutCompanyRequest.prototype.legalName = undefined;

/**
 * @member {String} fantasyName
 */
PutCompanyRequest.prototype.fantasyName = undefined;

/**
 * @member {String} registrationNumber
 */
PutCompanyRequest.prototype.registrationNumber = undefined;

/**
 * @member {module:model/RegistrationType} registrationType
 */
PutCompanyRequest.prototype.registrationType = undefined;

/**
 * @member {String} contactEmail
 */
PutCompanyRequest.prototype.contactEmail = undefined;

/**
 * @member {String} contactPhone
 */
PutCompanyRequest.prototype.contactPhone = undefined;

/**
 * @member {module:model/CompanyType} type
 */
PutCompanyRequest.prototype.type = undefined;

/**
 * @member {String} biography
 */
PutCompanyRequest.prototype.biography = undefined;

/**
 * @member {String} id
 */
PutCompanyRequest.prototype.id = undefined;

/**
 * @member {module:model/ProfilePhotoRequest} profilePhoto
 */
PutCompanyRequest.prototype.profilePhoto = undefined;

