/*
 * Caspian.Yes4Track.Service API
 * Caspian.Yes4Track.Service API
 *
 * OpenAPI spec version: v1
 * Contact: admin@yes4track.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The SponsorContact model module.
 * @module model/SponsorContact
 * @version v1
 */
export class SponsorContact {
  /**
   * Constructs a new <code>SponsorContact</code>.
   * @alias module:model/SponsorContact
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>SponsorContact</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SponsorContact} obj Optional instance to populate.
   * @return {module:model/SponsorContact} The populated <code>SponsorContact</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SponsorContact();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('phone'))
        obj.phone = ApiClient.convertToType(data['phone'], 'String');
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} name
 */
SponsorContact.prototype.name = undefined;

/**
 * @member {String} phone
 */
SponsorContact.prototype.phone = undefined;

/**
 * @member {String} email
 */
SponsorContact.prototype.email = undefined;

