/*
 * Caspian.Yes4Track.Service API
 * Caspian.Yes4Track.Service API
 *
 * OpenAPI spec version: v1
 * Contact: admin@yes4track.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Waypoint} from './Waypoint';

/**
 * The TrailGeoLocationDto model module.
 * @module model/TrailGeoLocationDto
 * @version v1
 */
export class TrailGeoLocationDto {
  /**
   * Constructs a new <code>TrailGeoLocationDto</code>.
   * @alias module:model/TrailGeoLocationDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>TrailGeoLocationDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TrailGeoLocationDto} obj Optional instance to populate.
   * @return {module:model/TrailGeoLocationDto} The populated <code>TrailGeoLocationDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TrailGeoLocationDto();
      if (data.hasOwnProperty('trailId'))
        obj.trailId = ApiClient.convertToType(data['trailId'], 'String');
      if (data.hasOwnProperty('lines'))
        obj.lines = ApiClient.convertToType(data['lines'], [['Number']]);
      if (data.hasOwnProperty('waypoints'))
        obj.waypoints = ApiClient.convertToType(data['waypoints'], [Waypoint]);
    }
    return obj;
  }
}

/**
 * @member {String} trailId
 */
TrailGeoLocationDto.prototype.trailId = undefined;

/**
 * @member {Array.<Array.<Number>>} lines
 */
TrailGeoLocationDto.prototype.lines = undefined;

/**
 * @member {Array.<module:model/Waypoint>} waypoints
 */
TrailGeoLocationDto.prototype.waypoints = undefined;

