/*
 * Caspian.Yes4Track.Service API
 * Caspian.Yes4Track.Service API
 *
 * OpenAPI spec version: v1
 * Contact: admin@yes4track.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {DocumentVersion} from './DocumentVersion';
import {GeoLocation} from './GeoLocation';
import {PushToken} from './PushToken';

/**
 * The User model module.
 * @module model/User
 * @version v1
 */
export class User {
  /**
   * Constructs a new <code>User</code>.
   * @alias module:model/User
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>User</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/User} obj Optional instance to populate.
   * @return {module:model/User} The populated <code>User</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new User();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('createdAt'))
        obj.createdAt = ApiClient.convertToType(data['createdAt'], 'Date');
      if (data.hasOwnProperty('updatedAt'))
        obj.updatedAt = ApiClient.convertToType(data['updatedAt'], 'Date');
      if (data.hasOwnProperty('userCreated'))
        obj.userCreated = ApiClient.convertToType(data['userCreated'], 'String');
      if (data.hasOwnProperty('userUpdated'))
        obj.userUpdated = ApiClient.convertToType(data['userUpdated'], 'String');
      if (data.hasOwnProperty('version'))
        obj.version = DocumentVersion.constructFromObject(data['version']);
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('phone'))
        obj.phone = ApiClient.convertToType(data['phone'], 'String');
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('photoUrl'))
        obj.photoUrl = ApiClient.convertToType(data['photoUrl'], 'String');
      if (data.hasOwnProperty('isActive'))
        obj.isActive = ApiClient.convertToType(data['isActive'], 'Boolean');
      if (data.hasOwnProperty('isAdmin'))
        obj.isAdmin = ApiClient.convertToType(data['isAdmin'], 'Boolean');
      if (data.hasOwnProperty('isSuperAdmin'))
        obj.isSuperAdmin = ApiClient.convertToType(data['isSuperAdmin'], 'Boolean');
      if (data.hasOwnProperty('isAngel'))
        obj.isAngel = ApiClient.convertToType(data['isAngel'], 'Boolean');
      if (data.hasOwnProperty('isExplorer'))
        obj.isExplorer = ApiClient.convertToType(data['isExplorer'], 'Boolean');
      if (data.hasOwnProperty('defaultAngel'))
        obj.defaultAngel = ApiClient.convertToType(data['defaultAngel'], 'String');
      if (data.hasOwnProperty('defaultSponsor'))
        obj.defaultSponsor = ApiClient.convertToType(data['defaultSponsor'], 'String');
      if (data.hasOwnProperty('companies'))
        obj.companies = ApiClient.convertToType(data['companies'], ['String']);
      if (data.hasOwnProperty('location'))
        obj.location = GeoLocation.constructFromObject(data['location']);
      if (data.hasOwnProperty('pushTokens'))
        obj.pushTokens = ApiClient.convertToType(data['pushTokens'], [PushToken]);
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
User.prototype.id = undefined;

/**
 * @member {Date} createdAt
 */
User.prototype.createdAt = undefined;

/**
 * @member {Date} updatedAt
 */
User.prototype.updatedAt = undefined;

/**
 * @member {String} userCreated
 */
User.prototype.userCreated = undefined;

/**
 * @member {String} userUpdated
 */
User.prototype.userUpdated = undefined;

/**
 * @member {module:model/DocumentVersion} version
 */
User.prototype.version = undefined;

/**
 * @member {String} name
 */
User.prototype.name = undefined;

/**
 * @member {String} phone
 */
User.prototype.phone = undefined;

/**
 * @member {String} email
 */
User.prototype.email = undefined;

/**
 * @member {String} photoUrl
 */
User.prototype.photoUrl = undefined;

/**
 * @member {Boolean} isActive
 */
User.prototype.isActive = undefined;

/**
 * @member {Boolean} isAdmin
 */
User.prototype.isAdmin = undefined;

/**
 * @member {Boolean} isSuperAdmin
 */
User.prototype.isSuperAdmin = undefined;

/**
 * @member {Boolean} isAngel
 */
User.prototype.isAngel = undefined;

/**
 * @member {Boolean} isExplorer
 */
User.prototype.isExplorer = undefined;

/**
 * @member {String} defaultAngel
 */
User.prototype.defaultAngel = undefined;

/**
 * @member {String} defaultSponsor
 */
User.prototype.defaultSponsor = undefined;

/**
 * @member {Array.<String>} companies
 */
User.prototype.companies = undefined;

/**
 * @member {module:model/GeoLocation} location
 */
User.prototype.location = undefined;

/**
 * @member {Array.<module:model/PushToken>} pushTokens
 */
User.prototype.pushTokens = undefined;

