/*
 * Caspian.Yes4Track.Service API
 * Caspian.Yes4Track.Service API
 *
 * OpenAPI spec version: v1
 * Contact: admin@yes4track.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {GeoLocation} from './GeoLocation';

/**
 * The UserResponse model module.
 * @module model/UserResponse
 * @version v1
 */
export class UserResponse {
  /**
   * Constructs a new <code>UserResponse</code>.
   * @alias module:model/UserResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>UserResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UserResponse} obj Optional instance to populate.
   * @return {module:model/UserResponse} The populated <code>UserResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UserResponse();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('phone'))
        obj.phone = ApiClient.convertToType(data['phone'], 'String');
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('photoUrl'))
        obj.photoUrl = ApiClient.convertToType(data['photoUrl'], 'String');
      if (data.hasOwnProperty('location'))
        obj.location = GeoLocation.constructFromObject(data['location']);
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
UserResponse.prototype.id = undefined;

/**
 * @member {String} name
 */
UserResponse.prototype.name = undefined;

/**
 * @member {String} phone
 */
UserResponse.prototype.phone = undefined;

/**
 * @member {String} email
 */
UserResponse.prototype.email = undefined;

/**
 * @member {String} photoUrl
 */
UserResponse.prototype.photoUrl = undefined;

/**
 * @member {module:model/GeoLocation} location
 */
UserResponse.prototype.location = undefined;

