/*
 * Caspian.Yes4Track.Service API
 * Caspian.Yes4Track.Service API
 *
 * OpenAPI spec version: v1
 * Contact: admin@yes4track.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {DocumentVersion} from './DocumentVersion';

/**
 * The VideoUrl model module.
 * @module model/VideoUrl
 * @version v1
 */
export class VideoUrl {
  /**
   * Constructs a new <code>VideoUrl</code>.
   * @alias module:model/VideoUrl
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>VideoUrl</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/VideoUrl} obj Optional instance to populate.
   * @return {module:model/VideoUrl} The populated <code>VideoUrl</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new VideoUrl();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('createdAt'))
        obj.createdAt = ApiClient.convertToType(data['createdAt'], 'Date');
      if (data.hasOwnProperty('updatedAt'))
        obj.updatedAt = ApiClient.convertToType(data['updatedAt'], 'Date');
      if (data.hasOwnProperty('userCreated'))
        obj.userCreated = ApiClient.convertToType(data['userCreated'], 'String');
      if (data.hasOwnProperty('userUpdated'))
        obj.userUpdated = ApiClient.convertToType(data['userUpdated'], 'String');
      if (data.hasOwnProperty('version'))
        obj.version = DocumentVersion.constructFromObject(data['version']);
      if (data.hasOwnProperty('fileName'))
        obj.fileName = ApiClient.convertToType(data['fileName'], 'String');
      if (data.hasOwnProperty('url'))
        obj.url = ApiClient.convertToType(data['url'], 'String');
      if (data.hasOwnProperty('sequence'))
        obj.sequence = ApiClient.convertToType(data['sequence'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
VideoUrl.prototype.id = undefined;

/**
 * @member {Date} createdAt
 */
VideoUrl.prototype.createdAt = undefined;

/**
 * @member {Date} updatedAt
 */
VideoUrl.prototype.updatedAt = undefined;

/**
 * @member {String} userCreated
 */
VideoUrl.prototype.userCreated = undefined;

/**
 * @member {String} userUpdated
 */
VideoUrl.prototype.userUpdated = undefined;

/**
 * @member {module:model/DocumentVersion} version
 */
VideoUrl.prototype.version = undefined;

/**
 * @member {String} fileName
 */
VideoUrl.prototype.fileName = undefined;

/**
 * @member {String} url
 */
VideoUrl.prototype.url = undefined;

/**
 * @member {Number} sequence
 */
VideoUrl.prototype.sequence = undefined;

