/*
 * Caspian.Yes4Track.Service API
 * Caspian.Yes4Track.Service API
 *
 * OpenAPI spec version: v1
 * Contact: admin@yes4track.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Caspianyes4TrackserviceApi);
  }
}(this, function(expect, Caspianyes4TrackserviceApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ActiveTrailResponse', function() {
      beforeEach(function() {
        instance = new Caspianyes4TrackserviceApi.ActiveTrailResponse();
      });

      it('should create an instance of ActiveTrailResponse', function() {
        // TODO: update the code to test ActiveTrailResponse
        expect(instance).to.be.a(Caspianyes4TrackserviceApi.ActiveTrailResponse);
      });

      it('should have the property trail (base name: "trail")', function() {
        // TODO: update the code to test the property trail
        expect(instance).to.have.property('trail');
        // expect(instance.trail).to.be(expectedValueLiteral);
      });

      it('should have the property user (base name: "user")', function() {
        // TODO: update the code to test the property user
        expect(instance).to.have.property('user');
        // expect(instance.user).to.be(expectedValueLiteral);
      });

      it('should have the property adventure (base name: "adventure")', function() {
        // TODO: update the code to test the property adventure
        expect(instance).to.have.property('adventure');
        // expect(instance.adventure).to.be(expectedValueLiteral);
      });

      it('should have the property status (base name: "status")', function() {
        // TODO: update the code to test the property status
        expect(instance).to.have.property('status');
        // expect(instance.status).to.be(expectedValueLiteral);
      });

    });
  });

}));
