/*
 * Caspian.Yes4Track.Service API
 * Caspian.Yes4Track.Service API
 *
 * OpenAPI spec version: v1
 * Contact: admin@yes4track.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Caspianyes4TrackserviceApi);
  }
}(this, function(expect, Caspianyes4TrackserviceApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('TrackGeoLocationDto', function() {
      beforeEach(function() {
        instance = new Caspianyes4TrackserviceApi.TrackGeoLocationDto();
      });

      it('should create an instance of TrackGeoLocationDto', function() {
        // TODO: update the code to test TrackGeoLocationDto
        expect(instance).to.be.a(Caspianyes4TrackserviceApi.TrackGeoLocationDto);
      });

      it('should have the property experiences (base name: "experiences")', function() {
        // TODO: update the code to test the property experiences
        expect(instance).to.have.property('experiences');
        // expect(instance.experiences).to.be(expectedValueLiteral);
      });

      it('should have the property trackId (base name: "trackId")', function() {
        // TODO: update the code to test the property trackId
        expect(instance).to.have.property('trackId');
        // expect(instance.trackId).to.be(expectedValueLiteral);
      });

      it('should have the property adventureId (base name: "adventureId")', function() {
        // TODO: update the code to test the property adventureId
        expect(instance).to.have.property('adventureId');
        // expect(instance.adventureId).to.be(expectedValueLiteral);
      });

      it('should have the property lines (base name: "lines")', function() {
        // TODO: update the code to test the property lines
        expect(instance).to.have.property('lines');
        // expect(instance.lines).to.be(expectedValueLiteral);
      });

      it('should have the property waypoints (base name: "waypoints")', function() {
        // TODO: update the code to test the property waypoints
        expect(instance).to.have.property('waypoints');
        // expect(instance.waypoints).to.be(expectedValueLiteral);
      });

    });
  });

}));
