/*
 * Caspian.Yes4Track.Service API
 * Caspian.Yes4Track.Service API
 *
 * OpenAPI spec version: v1
 * Contact: admin@yes4track.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Caspianyes4TrackserviceApi);
  }
}(this, function(expect, Caspianyes4TrackserviceApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Caspianyes4TrackserviceApi.TrackApi();
  });

  describe('(package)', function() {
    describe('TrackApi', function() {
      describe('getByIdTrack', function() {
        it('should call getByIdTrack successfully', function(done) {
          // TODO: uncomment, update parameter values for getByIdTrack call and complete the assertions
          /*
          var opts = {};

          instance.getByIdTrack(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Caspianyes4TrackserviceApi.GetAllTrackResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getByIdTrackGeoData', function() {
        it('should call getByIdTrackGeoData successfully', function(done) {
          // TODO: uncomment, update parameter values for getByIdTrackGeoData call
          /*
          var opts = {};

          instance.getByIdTrackGeoData(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getByIdTrackGeoLocation', function() {
        it('should call getByIdTrackGeoLocation successfully', function(done) {
          // TODO: uncomment, update parameter values for getByIdTrackGeoLocation call and complete the assertions
          /*
          var opts = {};

          instance.getByIdTrackGeoLocation(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(Caspianyes4TrackserviceApi.TrackGeoLocationDto);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('yes4trackV1TracksGet', function() {
        it('should call yes4trackV1TracksGet successfully', function(done) {
          // TODO: uncomment, update parameter values for yes4trackV1TracksGet call and complete the assertions
          /*
          var opts = {};

          instance.yes4trackV1TracksGet(adventureId, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Caspianyes4TrackserviceApi.GetAllPagedTrackResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('yes4trackV1TracksIdDelete', function() {
        it('should call yes4trackV1TracksIdDelete successfully', function(done) {
          // TODO: uncomment, update parameter values for yes4trackV1TracksIdDelete call
          /*
          var opts = {};

          instance.yes4trackV1TracksIdDelete(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('yes4trackV1TracksIdGeodataPost', function() {
        it('should call yes4trackV1TracksIdGeodataPost successfully', function(done) {
          // TODO: uncomment, update parameter values for yes4trackV1TracksIdGeodataPost call and complete the assertions
          /*
          var opts = {};

          instance.yes4trackV1TracksIdGeodataPost(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Caspianyes4TrackserviceApi.PostTrackGeoDataResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('yes4trackV1TracksIdPatch', function() {
        it('should call yes4trackV1TracksIdPatch successfully', function(done) {
          // TODO: uncomment, update parameter values for yes4trackV1TracksIdPatch call
          /*
          var opts = {};

          instance.yes4trackV1TracksIdPatch(body, id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('yes4trackV1TracksIdPut', function() {
        it('should call yes4trackV1TracksIdPut successfully', function(done) {
          // TODO: uncomment, update parameter values for yes4trackV1TracksIdPut call
          /*
          var opts = {};

          instance.yes4trackV1TracksIdPut(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('yes4trackV1TracksIdStatisticPut', function() {
        it('should call yes4trackV1TracksIdStatisticPut successfully', function(done) {
          // TODO: uncomment, update parameter values for yes4trackV1TracksIdStatisticPut call
          /*
          var opts = {};

          instance.yes4trackV1TracksIdStatisticPut(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('yes4trackV1TracksPost', function() {
        it('should call yes4trackV1TracksPost successfully', function(done) {
          // TODO: uncomment, update parameter values for yes4trackV1TracksPost call and complete the assertions
          /*
          var opts = {};

          instance.yes4trackV1TracksPost(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Caspianyes4TrackserviceApi.PostTrackResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
